version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  spring-app:
    image: openjdk:17-jdk-alpine
    platform: linux/amd64
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - redis
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

networks:
  backend:
    driver: bridge
